### PR TITLE
chore: Improve table layout and styling

### LINKED ISSUE #297: Redesign confirmation screen and CFD detail screen
same goes for CFD details screen

image

- the ordering of the details is odd
- expiry shouldn't have a sat sign
- overall it can be a bit _nicer_, e.g. something like ItchySats :D 
- 
image

### PR DESCRIPTION
**Pull request by holzeis**
Screenshot 2022-11-22 at 15 44 17

resolves #297

### CODE REVIEW

**Review by da-kami — APPROVED** [review]
Nice! I like the design, way better!

I would have probably tried to align the items in the second column on the right, but that's not super important

**Comment by da-kami** [comment]
We might want to extract the `info` card that is used for the explanation to the user in other screens, I will see to do this on top of this PR!

**Comment by bonomat** [comment]
making some minor additional adjustments.

**Comment by bonomat** [comment]
> Nice! I like the design, way better!
> 
> I would have probably tried to align the items in the second column on the right, but that's not super important

I'm doing this right now :)

**Comment by da-kami** [comment]
> > Nice! I like the design, way better!
> > I would have probably tried to align the items in the second column on the right, but that's not super important
> 
> I'm doing this right now :)

Great! then I go on testing :)

**Comment by bonomat** [comment]
Minor changes: 

image

image

**Review by bonomat — APPROVED** [review]
I'm self-approving my changes :D

**Comment by bonomat** [comment]
bors +

**Pull request merged**
