### PR TITLE
feat: Generate lightning invoices

### PR DESCRIPTION
**Pull request by klochowicz**
- align the API to allow passing custom description when creating invoice
- Add a Flutter widget that allows creating an invoice. You can specify amount,
  expiry time, and add a custom description.
  It generates a QR code and allows you to copy invoice to clipboard.

### CODE REVIEW

**Comment by klochowicz** [comment]
Uploading create_invoice.mp4…

**Review by bonomat — APPROVED** [review]
Nice, can the maker actually pay it?

**Comment by klochowicz** [comment]
> Nice, can the maker actually pay it?

nope 😢 we need an outbound route from the maker to do so...
```
  {
    "status": 500,
    "title": "Failed to pay lightning invoice",
```

**Comment by bonomat** [comment]
> > Nice, can the maker actually pay it?
> 
> nope 😢 we need an outbound route from the maker to do so...
> 
> ```
>   {
>     "status": 500,
>     "title": "Failed to pay lightning invoice",
> ```

This exists: the channel will have funding on both sides...

**Comment by klochowicz** [comment]
> This exists: the channel will have funding on both sides...

I've updated the error log (somehow pasted without the last part, which was crucial) - seems there needs to be outbound route from the maker?

**Comment by bonomat** [comment]
> > This exists: the channel will have funding on both sides...
> 
> I've updated the error log (somehow pasted without the last part, which was crucial) - seems there needs to be outbound route from the maker?

If you have opened a channel from the taker to the maker using our protocol then there is funding on the side of the maker and paying should be possible. I think the problem is somewhere else. 

I tried your branch locally and it looks like it is working but the payment remains in `pending` state. Might just be a frontend issue?

image

**Pull request merged**
