### PR TITLE
feat: pull down to sync

### PR DESCRIPTION
**Pull request by bonomat**
Small feature on the way :)

https://user-images.githubusercontent.com/224613/204672346-f4b00e59-aa54-4a0a-bf97-0f6d707ee407.mov

### CODE REVIEW

**Review by da-kami — APPROVED** [review]
LGTM, eventually would be cool of we don't have to duplicate the code or `_pullRefresh`, but I think it does not matter for now :)

**Review by luckysori — APPROVED** [review]
Really cool little feature!

**Review by klochowicz — APPROVED** [review]

**Comment by klochowicz** [comment]
awesome, it certainly makes the app look more natively mobile. :)

**Pull request merged**
