### PR TITLE
feat: Add market view

### PR DESCRIPTION
**Pull request by klochowicz**
Embed a TradingView bitmex XBTUSD widget inside a webview.

Note: it works on Android/iOS. Desktop platforms get a placeholder that the
    functionality is not supported yet.

I've recorded in landscape, as it's much nicer for viewing charts like that 😁
https://user-images.githubusercontent.com/8319440/203267520-dd5b8835-12e2-4ca1-8aa9-579b5e8f081a.mov

### CODE REVIEW

**Comment by klochowicz** [comment]
@holzeis could you please verify that it works on Android too? (I don't have the emulator working...)

**Comment by holzeis** [comment]
> @holzeis could you please verify that it works on Android too? (I don't have the emulator working...)

It unfortunately does not work as is..

> The plugin webview_flutter_android requires Android SDK version 32.

I'll have a look if I can fix that.

**Comment by holzeis** [comment]
> I'll have a look if I can fix that.

This commit 596e0b4551294d27a6917d89f3a69f8055369f26 increases the android sdk versions, required by webview_flutter_android. Only downside we won't be compatible with android versions lower than 19.

**Review by holzeis — APPROVED** [review]
https://github.com/flutter/plugins/tree/main/packages/webview_flutter/webview_flutter

The webview_flutter plugin seems to be the far more popular option. No need to action, but leaving it here in case we want to pick it up again after the tournament.

**Comment by da-kami** [comment]
Does this mean we should merge this or not?
It works on iPhone?

**Comment by klochowicz** [comment]
> Does this mean we should merge this or not?
> It works on iPhone?

yes, we should merge it. it works on iPhone - see the video attached.

**Pull request merged**
