### PR TITLE
chore: rename services a bit

### PR DESCRIPTION
**Pull request by bonomat**
- cfd --> trading
- exchange --> combined in trading
- betting --> removed
- DCA --> added

Services updated
simulator_screenshot_FD250FCB-E0E1-4D05-8F49-7866DB93B629

Menu updated
simulator_screenshot_B34EE2D7-D2FD-4463-BEC9-58D652CC89AE

`My CFD` --> `Positions`
simulator_screenshot_CC3A6D43-BB77-4710-A1BF-4DCFDB415ADC

simulator_screenshot_8C03E01E-E18A-4BC0-867C-E2B5671053F7

### CODE REVIEW

**Review by klochowicz — APPROVED** [review]
**huge** improvement 👏

**Review by da-kami — APPROVED** [review]
👍

We could even remove the `Stacking` service group and just have the three - If we capture more things under the `Trading` screens (without the need of a screen separation here) then we might not need the grouping at all :)

**Review by holzeis — APPROVED** [review]

**Comment by luckysori** [comment]
bors ping

**Comment by luckysori** [comment]
bors retry

**Pull request merged**
