### PR TITLE
feat: Persist lightning payments in sqlite database

### PR DESCRIPTION
**Pull request by klochowicz**
Sending and creating invoices had to change to `async` due to sqlx async nature.

### CODE REVIEW

**Review by luckysori — APPROVED** [review]
LGTM!

Does this PR close any issue?

**Comment by klochowicz** [comment]
> LGTM!
> 
> Does this PR close any issue?

yes, in github you can set it in the "Development" section - see the attached screenshot:
image

**Comment by luckysori** [comment]
>> Does this PR close any issue?

> yes


Lol, I missed it again.

> yes, in github you can set it in the "Development" section

Lol, I missed it again. I'm so used to looking for it in the PR description.

**Review by da-kami — APPROVED** [review]

**Pull request merged**
