### PR TITLE
chore: Do not specify maker peer info manually

### PR DESCRIPTION
**Pull request by klochowicz**
Pass in the hard-coded values to flutter. Expose them in the API so that they
     can be displayed.

### CODE REVIEW

**Comment by holzeis** [comment]
I don't think thats the right approach. We should pass the configuration using the cli. see also https://github.com/itchysats/10101/pull/215

**Review by holzeis — CHANGES_REQUESTED** [review]
I think we can skip that PR in favour of https://github.com/itchysats/10101/pull/215

**Comment by klochowicz** [comment]
> I think we can skip that PR in favour of #215

is there anything wrong with this PR? you've requested changes. If your one goes further, then it always can be rebased on top.

**Comment by da-kami** [comment]
> I think we can skip that PR in favour of #215

I think it is totally fine to do this in rust, and doing it in flutter makes our life harder because we have to communicate it to rust.

**Review by da-kami — APPROVED** [review]

**Comment by holzeis** [comment]
> > I think we can skip that PR in favour of #215
> 
> I think it is totally fine to do this in rust, and doing it in flutter makes our life harder because we have to communicate it to rust.

I prefer a configurable app over setting hardcoded configs.

**Pull request merged**
