### PR TITLE
feat: allow collab close channel through api

### PR DESCRIPTION
**Pull request by bonomat**
to force close call: 

```
curl -X POST http://localhost:8000/api/channel/close/0244946473b7926c427be70925e8e99cafc3ea76dffe708e6cba8896576cf0b14d\?force\=true
```

to collab close call

```
curl -X POST http://localhost:8000/api/channel/close/0244946473b7926c427be70925e8e99cafc3ea76dffe708e6cba8896576cf0b14d
```

### CODE REVIEW

**Review by luckysori — APPROVED** [review]

**Review by holzeis — APPROVED** [review]
Nice 👍 I like the query parameter 🙂

**Review by klochowicz — APPROVED** [review]
looks good! force-closing being a bit hidden is actually pretty nice.

**Comment by luckysori** [comment]
bors retry

**Pull request merged**
