### PR TITLE
Add service selector to dashboard

### PR DESCRIPTION
**Pull request by da-kami**
Includes navigation to CFD Trading screen, but we need more complex routing and should plug in a routing library as recommended here: https://docs.flutter.dev/development/ui/navigation#using-the-navigator

Screenshot 2022-11-01 at 3 07 23 pm

I will work on introducing [go_router routing library](https://pub.dev/packages/go_router) so we can depict the routing between the wallet and the service screens. 

Note on naming: I don't particularly like the name `service` for trading/bets (...) - I thought about different names (e.g. `feature` or `in-app-...?`) but did not come up with anything satisfying so I just went with `service` for now.

### CODE REVIEW

**Review by holzeis — APPROVED** [review]
Thank you, LGTM 👍

**Comment by klochowicz** [comment]
is this still a draft? (the description hints that, but it's not marked as draft) - in other words: should I review it or are you planning to add to it?

**Comment by da-kami** [comment]
> is this still a draft? (the description hints that, but it's not marked as draft) - in other words: should I review it or are you planning to add to it?

It is not a draft. Sorry if the description is misleading, for me it does not read like a draft - the work on the router was plugged on top in a separate PR so we can get this work in already :)

**Comment by klochowicz** [comment]
thanks for explanation, feel free to go ahead with it if it's needed :)

**Pull request merged**
