### PR TITLE
Add maker binary

### PR DESCRIPTION
**Pull request by klochowicz**
First cut of the binary. So far it just initialises the tracing and wallet (and then exits).
Posting now to make sure we're on the same page with the structure.

### CODE REVIEW

**Comment by klochowicz** [comment]
note: I have found a way to make the reuse least impactful for us (no changes from the perspective of rust lib, other than making some modules public; so no rebase conflict risk).

**Review by holzeis — APPROVED** [review]
Thanks 👍

**Comment by klochowicz** [comment]
merging this, so we can unlock all the other tickets depending on having the binary.

**Pull request merged**
